name: Mirror to Codeberg

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          remote: git@codeberg.org:opendesk-edu/opendesk-edu-website.git
          remote_name: codeberg
          git_push_args: --tags --force --prune
          git_ssh_no_verify_host: true
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG_SSH_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.CODEBERG_SSH_KNOWN_HOSTS }}
